# Final Words

Now we are going to runa  regression on 

```{r, cache = TRUE, message=FALSE, error=TRUE}

#----load all the libraries needed
# load in libraries
library(tidyverse)
library(scales)
library(lubridate)
library(ggridges)
library(gridExtra)

#regression
library(corrplot)
library(rgdal)
library(spdep)
library(car)

#----data visualization packages - https://serialmentor.com/dataviz/geospatial-data.html

#install.packages("remotes")
#install.packages("devtools")
library(remotes)

#install.packages("cowplot")
#devtools::install_github("wilkelab/cowplot")
library(cowplot)

#install.packages("colorspace")
library(colorspace)

#devtools::install_github("clauswilke/colorblindr")
#https://rdrr.io/github/clauswilke/dviz.supp/
#devtools::install_github("clauswilke/dviz.supp")
library(dviz.supp)

options(scipen = 999)
```



```{r, cache = TRUE, message=FALSE, error=TRUE}

#londonLSOAProfiles_inner <- londonLSOAProfiles[londonLSOAProfiles$'InnerOuter' == "Inner London"]

#londonLSOAProfiles_inner <- subset(londonLSOAProfiles, InnerOuter == "Inner London")

#---SUPPLY SIDE

#run a final OLS model
model_freq <- lm(log(`airbnb_freq`) ~ 
                    `bame_p` +
                    `nonUK` +
                    `education` +
                    `income` +
                    `house_mortg` +
                    `house_price` +
                    log(culture_freq) +
                    `culture_rating` +
                    log(culture_no_reviews) +
                    `InnerOuter`,
                  data = londonLSOAProfiles, na.action=na.exclude)

summary(model_freq)
```


```{r, cache = TRUE, message=FALSE, error=TRUE}

#and for future use, write the residuals out to a column in your dataframe

londonLSOAProfiles$model_freq_resids <- residuals(model_freq)
```


```{r, cache = TRUE, message=FALSE, error=TRUE}

# #https://stackoverflow.com/questions/6882709/how-do-i-deal-with-nas-in-residuals-in-a-regression-in-r
# #how to deal with residuals with NA - make use of the row names associated with the data frame provided as input to lm
# #londonLSOAProfiles[names(model_price$model_price_resids), "residual"] < - model_price$residuals
# 
# #use the boom library for residuals - https://stackoverflow.com/questions/17216358/eliminating-nas-from-a-ggplot
# library(broom)
# df <- augment(model_freq)

londonLSOAProfiles %>% 
  drop_na(model_freq_resids) %>%
      ggplot(aes(x= model_freq_resids)) +
      geom_histogram(alpha = 0.5, fill = "#5EB296", colour = "#4D4D4D") +
      scale_y_continuous(labels = comma) +
      ggtitle("RESIDUAL DISTRUBUTION", subtitle = "Residual distrubution of the Airbnb Price model") +
      labs(x= "log(Airbnb Freq)", y= "Count")

```

```{r, cache = TRUE, message=FALSE, error=TRUE}

vif(model_freq)

```


```{r, cache = TRUE, message=FALSE, error=TRUE}

#plot(model_freq)

```



```{r, cache = TRUE, message=FALSE, error=TRUE}

#nona <- londonLSOAProfiles[londonLSOAProfiles$model_freq_resids != 0]

#run durbin-watson test
durbinWatsonTest(model_freq$residuals)
```


```{r, cache = TRUE, message=FALSE, error=TRUE}

library(sf)
library(tmap)

tm_shape(londonLSOAProfiles) +
  tm_polygons("model_freq_resids",
              palette = "RdYlBu")
```


```{r}

# tm_shape(londonLSOAProfiles[londonLSOAProfiles$InnerOuter == "Inner London"]) +
#   tm_polygons("model_freq_resids",
#               palette = "RdYlBu")
```




```{r}

#---DEMAND SIDE

#run a final OLS model
model_reviews <- lm(log(`airbnb_no_reviews`) ~
                    `bame_p` +
                    `nonUK` +
                    `education` +
                    `employees` +
                    `income` +
                    `house_mortg` +
                    `house_price` +
                    log(culture_freq) +
                    `culture_rating` +
                    log(culture_no_reviews) +
                    `InnerOuter`,
                  data = londonLSOAProfiles, na.action=na.exclude)

summary(model_reviews)

```


```{r}

# df <- augment(model_reviews)
# 
# df %>%
#   drop_na(.resid) %>%
#       ggplot(aes(x= .resid)) +
#       geom_histogram(alpha = 0.5, fill = "#5EB296", colour = "#4D4D4D") +
#       scale_y_continuous(labels = comma) +
#       ggtitle("RESIDUAL DISTRUBUTION", subtitle = "Residual distrubution of the Airbnb Price model") +
#       labs(x= "log(Airbnb Freq)", y= "Count")
```


```{r}

vif(model_reviews)
```










```{r}

#run a final OLS model
model_price <- lm(log(`airbnb_price`) ~
                    `bame_p` +
                    `nonUK` +
                    `education` +
                    `employees` +
                    `income` +
                    `house_mortg` +
                    `house_price` +
                    log(culture_freq) +
                    `culture_rating` +
                    log(culture_no_reviews) +
                    `InnerOuter`,
                  data = londonLSOAProfiles, na.action=na.exclude)

summary(model_price)

```

```{r}

# df <- augment(model_price)
# 
# df %>%
#   drop_na(.resid) %>%
#       ggplot(aes(x= .resid)) +
#       geom_histogram(alpha = 0.5, fill = "#5EB296", colour = "#4D4D4D") +
#       scale_y_continuous(labels = comma) +
#       ggtitle("RESIDUAL DISTRUBUTION", subtitle = "Residual distrubution of the Airbnb Price model") +
#       labs(x= "log(Airbnb Freq)", y= "Count")
```

```{r}

vif(model_price)
```






```{r}

#run a final OLS model
model_house_price <- lm(log(`house_price`) ~
                    `bame_p` +
                    `nonUK` +
                    `education` +
                    `employees` +
                    `income` +
                    `house_mortg` +
                    `house_price` +
                    log(culture_freq) +
                    `InnerOuter`,
                  data = londonLSOAProfiles, na.action=na.exclude)

summary(model_house_price)
```






